[features]
seeds = false
skip-lint = false

[programs.devnet]
blogs = "HaZ8bJqM9dps9UybLnRGgZ7hK5hnw6UULxQbXEyF5bzM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/nicosix/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
